# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: npm install
      - run: npx nuxt build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: page-artifact
          path: ./.output/public
      - name: Upload github-pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./.output/public
        
        
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract artifact
        run: |
          mkdir -p ./artifact
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: page-artifact
          path: ./artifact

      - name: List files in directory
        run: ls ./artifact
          

      #- name: Deploy to GitHub Pages
      #  uses: actions/deploy-pages@v4

      #- name: Sync files to FTP
      #  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #  with:
      #    server: "${{ secrets.SERVER_SFTP }}"
      #    username: "${{ secrets.FTP_USERNAME }}"
      #    password: "${{ secrets.FTP_PASSWORD }}"
      #    local-dir: "./public"
      #    server-dir: "/srv/www/fs2024_ranner/www/"
